module.exports = [
    {
        name: "Yosemite Valley Hiking",
        lat:  37.865101,
        long: -119.538330,
        city: "Yosemite",
        state: "CA",
        date: '2021-05-03',
        creator: "Nicholas", 
        maxAttendees: 15,
        attendees: [
            "Josh",
            "Amanda",
            "Adam",
            "robot",
            "ejhiker",
            "pizzacat"
        ],
        details:{
            difficulty: 3, 
            activityType: "Hiking",
            supplies: ["Lunch", "Water"],
            description: "Hey guys it's Nick.  On May 5th (Wednesday), I'm gonna go hiking in the Yosemite Valley. Beginners are welcome but prepare for a long day, bring lunch."
        },
        img: "https://www.nps.gov/yose/planyourvisit/images/hiker-in-valleyweb.jpg?maxwidth=1200&maxheight=1200&autorotate=false",
    },
    {
        name: "Haleakala Shuttle Mountain Biking",
        lat:   20.701283,
        long: -156.173325,
        city: "Makawao",
        state: "HI",
        date: new Date('April 28, 2021 16:30:00'),
        creator: "Ellyn", 
        maxAttendees: 10,
        attendees: ["Bob", "Sarah", "Julia"], 
        details:{
            difficulty: 4, 
            activityType: "Mountain Biking",
            supplies: ["Bike", "Water", "Snacks"],
            description: "Hi everyone, I'm gonna be hosting a Mountain Biking event at Haleakala National Park in Hawaii on Wednesday April 28th. Hope everyone can make it!"
        },
        img: "https://cdn2.apstatic.com/photos/mtb/5079795_medium_1554329691.jpg",
    },
    {
        name: "Greenburgh Nature Center",
        lat:  37.865101,
        long: -119.538330,
        city: "Scarsdale",
        state: "NY",
        date: new Date('May 01, 2921 14:00:00'),
        creator: "Jazmyne", 
        maxAttendees: 5,
        attendees: [],
        details:{
            difficulty: 1, 
            activityType: "Walking",
            supplies: ["Water", "Snacks"],
            description: "Hi, on May 1st I'll be taking a short walk through the Greenburgh Nature Center woodland trail. Super easy, all are welcome."
        },
        img: "https://redtri.com/wp-content/uploads/2014/08/greenburgh-nature-center-fall1.jpg",
    },
    {
        details: {
            supplies: [
            'Snacks',
            'Water',
            'Hiking Shoes',
            'Warm Layer',
            ],
            difficulty: 1,
            activityType: 'Hiking',
            description: 'chill fells walk',
        },
        name: 'Walk at the Middlesex Fells Reservation',
        attendees: [
            'marshall',
            'ejhiker',
        ],
        city: 'Somerville',
        state: 'MA',
        date: '2021-05-05T00:00:00.000Z',
        creator: 'ejhiker',
        maxAttendees: 5,
        img: 'https://thetravellingsquid.com/wp-content/uploads/2020/12/PXL_20201010_155526968.jpg',
    },
   {
        details: {
            supplies: [],
            difficulty: 1,
            activityType: 'Hiking',
            description: 'chill fells walk',
        },
        name: 'Walk at the Middlesex Fells Reservation',
        attendees: [
            'pizzacat',
        ],
        city: 'Somerville',
        state: 'MA',
        date: '2021-05-05T00:00:00.000Z',
        creator: 'robot',
        maxAttendees: 5,
        img: 'https://cdn-assets.alltrails.com/uploads/photo/image/35610030/extra_large_fd1b7e1e97e13fac2df1640c7828d1c7.jpg',
    },
    {
        details: {
            supplies: [],
            difficulty: 1,
            activityType: 'Hiking',
            description: 'chill fells walk',
        },
        name: 'Walk at the Middlesex Fells Reservation',
        attendees: [],
        city: 'Somerville',
        state: 'MA',
        date: '2021-05-05T00:00:00.000Z',
        creator: 'ejhiker',
        maxAttendees: 5,
        img: 'https://media-cdn.tripadvisor.com/media/photo-s/17/2e/42/30/tranquility-by-the-lake.jpg',
    },
    {
        details: {
            supplies: [],
            difficulty: 1,
            activityType: 'Hiking',
            description: 'chill fells walk',
        },
        name: 'Walk at the Middlesex Fells Reservation',
        attendees: [],
        city: 'Somerville',
        state: 'MA',
        date: '2021-05-05T00:00:00.000Z',
        creator: 'ejhiker',
        maxAttendees: 5,
        img: 'https://cdn-assets.alltrails.com/uploads/photo/image/21054218/extra_large_fa8ee11a990dbea800a0d63e7f918f1c.jpg',
    },
    {
        details: {
            supplies: [],
            difficulty: 1,
            activityType: 'Hiking',
            description: 'chill fells walk',
        },
        name: 'Walk at the Middlesex Fells Reservation',
        attendees: [
            'ejhiker',
        ],
        city: 'Somerville',
        state: 'MA',
        date: '2021-05-05T00:00:00.000Z',
        creator: 'ejhiker',
        maxAttendees: 5,
        img: 'https://www.nhmountainhiking.com/hike/middlesex/signage.jpg',
    },
    {
        details: {
            supplies: [],
            difficulty: 4,
            activityType: 'Hiking',
            description: 'hard hike up a 4000 footer',
        },
        name: 'Hike Mt Adams',
        attendees: [
            'ejhiker',
        ],
        city: 'Gorham',
        state: 'NH',
        date: '2021-05-01T00:00:00.000Z',
        creator: 'ejhiker',
        maxAttendees: 5,
        img: 'https://www.hikenewengland.com/images/Adams070908-7.jpg',
    },
    {
        details: {
            supplies: [],
            difficulty: 1,
            activityType: 'Picnicking',
            description: 'picnic with strangers on the charles river',
        },
        name: 'Picnic on the Esplanade',
        attendees: [],
        city: 'Boston',
        state: 'MA',
        date: '2021-05-08T00:00:00.000Z',
        creator: 'ejhiker',
        maxAttendees: 10,
        img: 'https://intermountainhealthcare.org/-/media/images/modules/blog/posts/2017/08/what-to-pack-for-a-healthy-picnic.jpg?la=en&h=505&w=896&mw=896&hash=9AFE3E6B852BD064E38196E091457863ADC7C079',
    },
    {
        details: {
            supplies: [],
            difficulty: 1,
            activityType: 'Picnicking',
            description: 'Picnic!',
        },
        name: 'Picnic on the Esplanade',
        attendees: [],
        city: 'Boston',
        state: 'MA',
        date: '2021-05-08T00:00:00.000Z',
        creator: 'ejhiker',
        maxAttendees: 10,
        img: 'https://intermountainhealthcare.org/-/media/images/modules/blog/posts/2017/08/what-to-pack-for-a-healthy-picnic.jpg?la=en&h=505&w=896&mw=896&hash=9AFE3E6B852BD064E38196E091457863ADC7C079',
    },
    {
        details: {
            supplies: [],
            difficulty: 1,
            activityType: 'Picnicking',
            description: 'Picnic!',
        },
        name: 'Picnic on the Esplanade',
        attendees: [],
        city: 'Boston',
        state: 'MA',
        date: '2021-05-08T00:00:00.000Z',
        creator: 'ejhiker',
        maxAttendees: 10,
        img: 'https://intermountainhealthcare.org/-/media/images/modules/blog/posts/2017/08/what-to-pack-for-a-healthy-picnic.jpg?la=en&h=505&w=896&mw=896&hash=9AFE3E6B852BD064E38196E091457863ADC7C079',
    },
    {
        details: {
            supplies: [],
            difficulty: 2,
            activityType: "Kayaking/Canoeing",
            description: "water will happen"
        },
        name: "Beginner Sea Kayaking",
        attendees: [],
        city: "Portland",
        state: "ME",
        date: "2021-06-05T00:00:00.000Z",
        creator: "ejhiker",
        maxAttendees: 10,
        img: "https://www.lapintagalapagoscruise.com/wp-content/uploads/2017/03/kayaking-espanola-island-galapagos-islands.jpg",
    },
    {
        details: {
            supplies: [
            'Climbing Rope',
            'Chalk',
            'Climbing Shoes',
            'Harness',
            ],
            difficulty: 1,
            activityType: 'Climbing',
            description: 'Appropriate for all levels of skill -- if you dont have any gear, it is available for rent at the facility',
        },
        name: 'Indoor Climbing Gym',
        attendees: [
            'ejhiker',
        ],
        city: 'Somerville',
        state: 'MA',
        date: '2021-04-30T00:00:00.000Z',
        creator: 'ejhiker',
        maxAttendees: 10,
        img: 'https://philarockgym.com/prg-fishtown/wp-content/uploads/sites/12/2020/06/Screen-Shot-2018-12-11-at-2.05.45-PM.png',
    },
    {
        details: {
            supplies: [
            'Mountain Bike',
            'helmet',
            'water',
            'Snacks',
            ],
            difficulty: 2,
            activityType: 'Mountain Biking',
            description: 'aiming for a 6 mile bike loop in willowdale state forest. Beginner friendly!',
        },
        name: 'Willowdale State Forest',
        attendees: [],
        city: 'Essex',
        state: 'MA',
        date: '2021-05-08T00:00:00.000Z',
        creator: 'robot',
        maxAttendees: 5,
        img: 'https://essexheritage.org/sites/default/files/styles/attraction_full/public/willowdale_state_forest_5-m.jpg?itok=WRTvvN9T',
    },
    {
        details: {
            supplies: [
            'Helmet',
            'Warm Layer',
            'Lunch',
            'Skis',
            'Winter Clothes',
            ],
            difficulty: 1,
            activityType: 'Skiing/Snowboarding',
            description: 'Meet at the parking lot. We have ski passes for all 8 people and will be giving into skiing lessons to any who want them.',
        },
        name: 'Ski Trip to Wachussett',
        attendees: [
            'ejhiker',
            'pizzacat',
            'marshall',
        ],
        city: 'Princeton',
        state: 'MA',
        date: '2021-02-01T00:00:00.000Z',
        creator: 'ejhiker',
        maxAttendees: 8,
        img: 'https://www.bostonherald.com/wp-content/uploads/migration/2018/01/06/010618skiJP16.jpg',
    },
    {
        details: {
            supplies: [
            'Snacks',
            'Hiking Boots',
            ],
            difficulty: 1,
            activityType: 'Hiking',
            description: 'About a 4 mile easy walking loop. Dogs are welcome!',
        },
        name: 'Harold Parker Walk',
        attendees: [
            'pizzacat',
        ],
        city: 'Andover',
        state: 'MA',
        date: '2021-04-30T00:00:00.000Z',
        creator: 'ejhiker',
        maxAttendees: 5,
        img: 'https://www.bostonmagazine.com/wp-content/uploads/2015/09/5-Harold-Parker-State-Forest-Photo-courtesy-of-Bud-Marvel-on-Flickr.jpg',
    },
    {
        details: {
            supplies: [
                "Hiking Boots",
                "Snacks"
            ],
            difficulty: 1,
            activityType: "Hiking",
            description: "4 mile easy walking route welcome to all ages and dogs!"
        },
        name: "Harold Parker Walk",
        attendees: [
            "ejhiker"
        ],
        city: "Andover",
        state: "MA",
        date: "2021-04-09T00:00:00.000Z",
        creator: "ejhiker",
        maxAttendees: 5,
        img: "https://www.bostonmagazine.com/wp-content/uploads/2015/09/5-Harold-Parker-State-Forest-Photo-courtesy-of-Bud-Marvel-on-Flickr.jpg",
    },
    {
        details: {
            supplies: [
            'Snacks',
            'Blanket',
            ],
            difficulty: 1,
            activityType: 'Picnicking',
            description: 'Lets look at trees together and have a picnic on a hill',
        },
        name: 'The Arnold Arboretum',
        attendees: [
            'marshall',
        ],
        city: 'Jamaica Plain',
        state: 'MA',
        date: '2021-05-01T00:00:00.000Z',
        creator: 'marshall',
        maxAttendees: 6,
        img: 'https://www.publicgardens.org/sites/default/files/styles/1000x400_garden_image/public/images/Garden/Arnold%20Arboretum%20of%20Harvard%20University.jpg?itok=Kc0IDcum',
    }
]
